function concatenar() {
  var temp1 = getTemp();
  var temp2 = getTemp();
  var temp3 = getTemp();
  var temp4 = getTemp();
  agregar3d("$$_concatenar(){");
  agregar3d(temp3 + " = p + 1;");
  agregar3d(temp1 + " = stack[" + temp3 + "];");
  agregar3d(temp4 + " = p + 2;");
  agregar3d(temp2 + " = stack[" + temp4 + "];");
  var tempRef = getTemp();
  var tempCont = getTemp();
  var linicio = getEtq();
  var tempVal = getTemp();
  var lv = getEtq();
  var lf = getEtq();
  agregar3d(tempRef + " = h;");
  agregar3d("h = h + 1;");
  agregar3d("heap[" + tempRef + "] = s;");
  agregar3d(tempCont + " = heap[" + temp1 + "];");
  agregar3d(linicio + ":");
  agregar3d(tempVal + " = pool[" + tempCont + "]");
  agregar3d("if( " + tempVal + " != 0 ) goto " + lv +";");
  agregar3d("goto " + lf + ";");
  agregar3d(lv + ":");
  agregar3d("pool[s] = " + tempVal + ";");
  agregar3d("s = s + 1;");
  agregar3d(tempCont + " = " + tempCont + " + 1;");
  agregar3d("goto " + linicio + ";");
  agregar3d(lf + ":");
  agregar3d("//se recorre la 2da cadena para concatenar");
  tempCont = getTemp();
  linicio = getEtq();
  tempVal = getTemp();
  lv = getEtq();
  lf = getEtq();
  agregar3d(tempCont + " = heap[" + temp2 + "];");
  agregar3d(linicio + ":");
  agregar3d(tempVal + " = pool[" + tempCont + "]");
  agregar3d("if( " + tempVal + " != 0 ) goto " + lv +";");
  agregar3d("goto " + lf + ";");
  agregar3d(lv + ":");
  agregar3d("pool[s] = " + tempVal + ";");
  agregar3d("s = s + 1;");
  agregar3d(tempCont + " = " + tempCont + " + 1;");
  agregar3d("goto " + linicio + ";");
  agregar3d(lf + ":");
  agregar3d("pool[s] = 0;");
  agregar3d("s = s + 1;");
  var tempRet = getTemp();
  agregar3d(tempRet + " = p + 0");
  agregar3d("stack[" + tempRet + "] = " + tempRef);
  agregar3d("}");
}

function convertirNumAStr() {
  var t1 = getTemp();
  var t2 = getTemp();
  var t3 = getTemp();
  var t4 = getTemp();
  var t5 = getTemp();
  var t6 = getTemp();
  var t7 = getTemp();
  var t8 = getTemp();
  var t9 = getTemp();
  var t10 = getTemp();
  var t11 = getTemp();
  var tx = getTemp();
  var tempRef = getTemp();
  var l1 = getEtq();
  var l2 = getEtq();
  var l3 = getEtq();
  var l4 = getEtq();
  var l5 = getEtq();
  var l6 = getEtq();
  var l7 = getEtq();
  var l8 = getEtq();
  var lconteo = getEtq();
  var lciclo1 = getEtq();
  var lciclo2 = getEtq();
  agregar3d("$$_convertirNumAStr(){");
  agregar3d(tempRef + " = h;");
  agregar3d("h = h + 1;");
  agregar3d("heap[" + tempRef + "] = s;");
  agregar3d(tx + " = p + 1;");
  agregar3d(t1 + " = stack[" + tx + "];");
  agregar3d(t2 + " = 1;");
  agregar3d("//------=>etiqueta de conteo");
  agregar3d(lconteo + ":");
  agregar3d("if( " + t2 + " < " + t1 + " ) goto " + l1 + ";");
  agregar3d("goto " + l2 + ";");
  agregar3d(l1 + ":");
  agregar3d(t2 + " = " + t2 + " * 10;");
  agregar3d("goto " + lconteo + ";");
  agregar3d(l2 + ":");
  agregar3d("//------=>etiqueta de ciclo1");
  agregar3d(lciclo1 + ":");
  agregar3d(t2 + " = " + t2 + " / 10;");
  agregar3d("if( " + t1 + " > 1 ) goto " + l3 + ";");
  agregar3d("goto " + l4 + ";");
  agregar3d(l3 + ":");
  agregar3d(t3 + " = " + t1 + " % " + t2 + ";");
  agregar3d(t4 + " = " + t1 + " - " + t3 + ";");
  agregar3d(t5 + " = " + t4 + " / " + t2 + ";");
  agregar3d(t6 + " = " + t5 + " + 48;");
  agregar3d("pool[s] = " + t6 + ";");
  agregar3d("s = s + 1;");
  agregar3d(t1 + " = " + t1 + " - " + t4 + ";");
  agregar3d("goto " + lciclo1 + ";");
  agregar3d("if( " + t1 + " > 0 ) goto " + l5 + ";");
  agregar3d("goto " + l6 + ";");
  agregar3d(l5 + ":");
  agregar3d("pool[s] = " + ".".charCodeAt(0) + ";");
  agregar3d("s = s + 1;");
  agregar3d("//------=>etiqueta de ciclo2");
  agregar3d(lciclo2 + ":");
  agregar3d(t1 + " = " + t1 + " * 10;");
  agregar3d("if( " + t1 + " > 0 ) goto " + l7 + ";");
  agregar3d("goto " + l8 + ";");
  agregar3d(l7 + ":");
  agregar3d(t8 + " = " + t1 + " % 1;");
  agregar3d(t9 + " = " + t1 + " - " + t8 + ";");
  agregar3d(t10 + " = " + t9 + " + 48;");
  agregar3d("pool[s] = " + t10 + ";");
  agregar3d("s = s + 1;");
  agregar3d(t1 + " = " + t8 + ";");
  agregar3d("goto " + lciclo2 + ";");
  agregar3d(l8 + ":");
  agregar3d(l6 + ":");
  agregar3d("pool[s] = 0;");
  agregar3d("s = s + 1;");
  agregar3d(t11 + " = p + 0;");
  agregar3d("stack[" + t11 + "] = " + tempRef + ";");
  agregar3d("}");
}

function crearMetodosEstandar() {
  convertirNumAStr();
  concatenar();
}
